### ISSUE TITLE
ExtensionManager has wrong handling of extenstion

### ISSUE THREAD

**Issue by larseidam** [AKSW/OntoWiki#167] opened 2012-11-28 12:08 UTC
All extensions are shown as deactivated although some of the extensions are active. If you enable an extension nothing happens.

This problem was first occurs with the jquery update from commit c81bf94. Before this commit everything was fine.

**Comment by white-gecko** [comment] 2016-02-29 16:31
@shinobu could you please see if this issue still exists, if not please close it

**Comment by shinobu** [comment] 2016-03-06 15:59
can't reproduce the issue -> closed

**Closed by shinobu** 2016-03-06 15:59 UTC
Labels: priority / major
